"""Initial migration

Revision ID: 5709da58d07c
Revises: 
Create Date: 2024-10-29 10:22:13.470088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5709da58d07c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_name'), 'children', ['name'], unique=True)
    op.create_table('drinking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinking_name'), 'drinking', ['name'], unique=True)
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currently_studying', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_name'), 'employment', ['name'], unique=True)
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gender_name'), 'gender', ['name'], unique=True)
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personality_name'), 'personality', ['name'], unique=True)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=True)
    op.create_table('relationshipstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationshipstatus_name'), 'relationshipstatus', ['name'], unique=True)
    op.create_table('religion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_religion_name'), 'religion', ['name'], unique=True)
    op.create_table('seeking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seeking_name'), 'seeking', ['name'], unique=True)
    op.create_table('sexuality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sexuality_name'), 'sexuality', ['name'], unique=True)
    op.create_table('smoking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smoking_name'), 'smoking', ['name'], unique=True)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supabase_uid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('children_id', sa.Integer(), nullable=True),
    sa.Column('drinking_id', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('personality_id', sa.Integer(), nullable=True),
    sa.Column('pets_id', sa.Integer(), nullable=True),
    sa.Column('relationship_status_id', sa.Integer(), nullable=True),
    sa.Column('religion_id', sa.Integer(), nullable=True),
    sa.Column('seeking_id', sa.Integer(), nullable=True),
    sa.Column('sexuality_id', sa.Integer(), nullable=True),
    sa.Column('smoking_id', sa.Integer(), nullable=True),
    sa.Column('employment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['children_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['drinking_id'], ['drinking.id'], ),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['employment.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['personality_id'], ['personality.id'], ),
    sa.ForeignKeyConstraint(['pets_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['relationship_status_id'], ['relationshipstatus.id'], ),
    sa.ForeignKeyConstraint(['religion_id'], ['religion.id'], ),
    sa.ForeignKeyConstraint(['seeking_id'], ['seeking.id'], ),
    sa.ForeignKeyConstraint(['sexuality_id'], ['sexuality.id'], ),
    sa.ForeignKeyConstraint(['smoking_id'], ['smoking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_gender_id'), 'profile', ['gender_id'], unique=False)
    op.create_index(op.f('ix_profile_supabase_uid'), 'profile', ['supabase_uid'], unique=True)
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['profile.supabase_uid'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['profile.supabase_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_blocked_id'), 'block', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_block_blocker_id'), 'block', ['blocker_id'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_profile_id'), 'image', ['profile_id'], unique=False)
    op.create_index(op.f('ix_image_url'), 'image', ['url'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_one_id', sa.Uuid(), nullable=False),
    sa.Column('user_two_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_one_id'], ['profile.supabase_uid'], ),
    sa.ForeignKeyConstraint(['user_two_id'], ['profile.supabase_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_user_one_id'), 'match', ['user_one_id'], unique=False)
    op.create_index(op.f('ix_match_user_two_id'), 'match', ['user_two_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chatroom.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['profile.supabase_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_chat_room_id'), 'message', ['chat_room_id'], unique=False)
    op.create_index(op.f('ix_message_sender_id'), 'message', ['sender_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profile.supabase_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('reported_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('action_taken', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['reported_id'], ['profile.supabase_uid'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['profile.supabase_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_reported_id'), 'report', ['reported_id'], unique=False)
    op.create_index(op.f('ix_report_reporter_id'), 'report', ['reporter_id'], unique=False)
    op.create_table('swipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swiper_id', sa.Uuid(), nullable=False),
    sa.Column('swiped_id', sa.Uuid(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['swiped_id'], ['profile.supabase_uid'], ),
    sa.ForeignKeyConstraint(['swiper_id'], ['profile.supabase_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swipe_swiped_id'), 'swipe', ['swiped_id'], unique=False)
    op.create_index(op.f('ix_swipe_swiper_id'), 'swipe', ['swiper_id'], unique=False)
    op.create_table('userpreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.Column('relationship_status_id', sa.Integer(), nullable=True),
    sa.Column('religion_id', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('smoking_id', sa.Integer(), nullable=True),
    sa.Column('drinking_id', sa.Integer(), nullable=True),
    sa.Column('pets_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drinking_id'], ['drinking.id'], ),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], ),
    sa.ForeignKeyConstraint(['pets_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['relationship_status_id'], ['relationshipstatus.id'], ),
    sa.ForeignKeyConstraint(['religion_id'], ['religion.id'], ),
    sa.ForeignKeyConstraint(['smoking_id'], ['smoking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userpreference_drinking_id'), 'userpreference', ['drinking_id'], unique=False)
    op.create_index(op.f('ix_userpreference_education_id'), 'userpreference', ['education_id'], unique=False)
    op.create_index(op.f('ix_userpreference_pets_id'), 'userpreference', ['pets_id'], unique=False)
    op.create_index(op.f('ix_userpreference_profile_id'), 'userpreference', ['profile_id'], unique=False)
    op.create_index(op.f('ix_userpreference_relationship_status_id'), 'userpreference', ['relationship_status_id'], unique=False)
    op.create_index(op.f('ix_userpreference_religion_id'), 'userpreference', ['religion_id'], unique=False)
    op.create_index(op.f('ix_userpreference_smoking_id'), 'userpreference', ['smoking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userpreference_smoking_id'), table_name='userpreference')
    op.drop_index(op.f('ix_userpreference_religion_id'), table_name='userpreference')
    op.drop_index(op.f('ix_userpreference_relationship_status_id'), table_name='userpreference')
    op.drop_index(op.f('ix_userpreference_profile_id'), table_name='userpreference')
    op.drop_index(op.f('ix_userpreference_pets_id'), table_name='userpreference')
    op.drop_index(op.f('ix_userpreference_education_id'), table_name='userpreference')
    op.drop_index(op.f('ix_userpreference_drinking_id'), table_name='userpreference')
    op.drop_table('userpreference')
    op.drop_index(op.f('ix_swipe_swiper_id'), table_name='swipe')
    op.drop_index(op.f('ix_swipe_swiped_id'), table_name='swipe')
    op.drop_table('swipe')
    op.drop_index(op.f('ix_report_reporter_id'), table_name='report')
    op.drop_index(op.f('ix_report_reported_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_message_sender_id'), table_name='message')
    op.drop_index(op.f('ix_message_chat_room_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_match_user_two_id'), table_name='match')
    op.drop_index(op.f('ix_match_user_one_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_image_url'), table_name='image')
    op.drop_index(op.f('ix_image_profile_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_block_blocker_id'), table_name='block')
    op.drop_index(op.f('ix_block_blocked_id'), table_name='block')
    op.drop_table('block')
    op.drop_index(op.f('ix_profile_supabase_uid'), table_name='profile')
    op.drop_index(op.f('ix_profile_gender_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_smoking_name'), table_name='smoking')
    op.drop_table('smoking')
    op.drop_index(op.f('ix_sexuality_name'), table_name='sexuality')
    op.drop_table('sexuality')
    op.drop_index(op.f('ix_seeking_name'), table_name='seeking')
    op.drop_table('seeking')
    op.drop_index(op.f('ix_religion_name'), table_name='religion')
    op.drop_table('religion')
    op.drop_index(op.f('ix_relationshipstatus_name'), table_name='relationshipstatus')
    op.drop_table('relationshipstatus')
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_personality_name'), table_name='personality')
    op.drop_table('personality')
    op.drop_table('location')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_table('languages')
    op.drop_table('interest')
    op.drop_index(op.f('ix_gender_name'), table_name='gender')
    op.drop_table('gender')
    op.drop_index(op.f('ix_employment_name'), table_name='employment')
    op.drop_table('employment')
    op.drop_table('education')
    op.drop_index(op.f('ix_drinking_name'), table_name='drinking')
    op.drop_table('drinking')
    op.drop_index(op.f('ix_children_name'), table_name='children')
    op.drop_table('children')
    op.drop_table('chatroom')
    # ### end Alembic commands ###
